spring.application.name=ledgerflow-api
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/ledgerflow
spring.datasource.username=ledgerflow
spring.datasource.password=ledgerflow_local_dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info