ALTER TABLE app_users DROP CONSTRAINT ck_app_users_role;
ALTER TABLE app_users ADD CONSTRAINT ck_app_users_role CHECK (role IN ('AUDITOR','OPERATOR','TREASURY_ADMIN','CUSTOMER'));
ALTER TABLE audit_events DROP CONSTRAINT audit_events_actor_role_check;
ALTER TABLE audit_events ADD CONSTRAINT audit_events_actor_role_check CHECK (actor_role IN ('AUDITOR','OPERATOR','TREASURY_ADMIN','CUSTOMER','SYSTEM'));
ALTER TABLE audit_events DROP CONSTRAINT audit_events_action_check;
ALTER TABLE audit_events ADD CONSTRAINT audit_events_action_check CHECK (action IN (
    'ACCOUNT_CREATED', 'ACCOUNT_FROZEN', 'ACCOUNT_UNFROZEN',
    'TRANSFER_COMPLETED', 'TREASURY_DEPOSIT', 'TRANSFER_REVERSED',
    'TRANSFER_REQUESTED', 'TRANSFER_APPROVED', 'TRANSFER_REJECTED',
    'USER_ROLE_CHANGED', 'SIMULATOR_TOPUP', 'CUSTOMER_TRANSFER_COMPLETED'
));
