"""Run against a local dev server. Tests mutate demo state only."""
import os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

BASE = os.environ.get("BASE_URL", "http://127.0.0.1:3100")
with sync_playwright() as p:
    browser = p.chromium.launch(headless=True)
    page = browser.new_page(viewport={"width": 1440, "height": 1000})
    page.set_default_timeout(15000)
    output = Path(__file__).parent / "artifacts"
    output.mkdir(exist_ok=True)
    errors = []
    page.on("pageerror", lambda error: errors.append(str(error)))
    page.goto(BASE + "/accounts")
    page.wait_for_load_state("networkidle")
    expect(page.get_by_role("heading", name="Accounts", exact=True)).to_be_visible()
    page.get_by_role("textbox", name="Search accounts").fill("GoPay")
    expect(page.locator("tbody tr")).to_have_count(1)
    page.get_by_role("button", name="Actions for GoPay Merchant Corporate Node").click()
    expect(page.get_by_role("menu")).to_contain_text("Allocate from treasury")
    page.keyboard.press("Escape")
    page.get_by_role("button", name="Clear filters").click()
    page.get_by_role("button", name="Create account", exact=True).click()
    dialog = page.get_by_role("dialog")
    dialog.get_by_label("Account name", exact=True).fill("Smoke test account")
    dialog.get_by_label("Opening balance", exact=False).fill("1000.25")
    dialog.get_by_role("button", name="Create account", exact=True).click()
    expect(dialog).not_to_be_visible()
    page.get_by_role("textbox", name="Search accounts").fill("Smoke test")
    expect(page.locator("tbody")).to_contain_text("Rp 1.000,25")
    page.get_by_role("link", name="Transfers", exact=True).click()
    page.get_by_role("combobox", name="Source account").click()
    page.get_by_role("option", name="BCA Corporate Primary Operating Vault").click()
    page.get_by_label("Destination account", exact=False).fill("10000000-0000-4000-8000-000000000002")
    page.get_by_label("Amount in IDR").fill("100.25")
    page.screenshot(path=str(output / "transfers-desktop.png"), full_page=True)
    page.get_by_role("button", name="Review transfer", exact=True).click()
    page.get_by_role("button", name="Confirm transfer", exact=True).click()
    expect(page.get_by_role("heading", name="Transfer completed")).to_be_visible()
    expect(page.get_by_role("listitem").filter(has_text="Transfer completed")).to_be_visible()
    expect(page.get_by_label("Source account", exact=False)).not_to_be_visible()
    page.get_by_role("link", name="View journal", exact=True).click()
    expect(page.locator("tbody tr")).to_have_count(1)
    page.locator("tbody tr button.link").click()
    expect(page.get_by_role("dialog")).to_contain_text("Balanced within the retrieved transaction entries.")
    page.screenshot(path=str(output / "ledger-desktop.png"), full_page=True)
    page.get_by_role("button", name="Close dialog").click()
    page.get_by_role("link", name="Treasury", exact=True).click()
    expect(page.get_by_role("heading", name="Treasury", exact=True)).to_be_visible()
    page.get_by_label("Target account", exact=False).fill("10000000-0000-4000-8000-000000000002")
    page.get_by_label("Amount in IDR").fill("5000000")
    page.get_by_label("Reason / audit note", exact=False).fill("Smoke test allocation")
    page.screenshot(path=str(output / "treasury-desktop.png"), full_page=True)
    page.get_by_role("button", name="Review allocation", exact=True).click()
    page.get_by_role("button", name="Confirm allocation", exact=True).click()
    expect(page.get_by_role("heading", name="Allocation completed")).to_be_visible()
    page.get_by_role("link", name="System status", exact=True).click()
    page.get_by_role("button", name="Refresh status", exact=True).click()
    expect(page.locator(".health-strip")).to_contain_text("Demo mode does not check real services.")
    page.screenshot(path=str(output / "status-desktop.png"), full_page=True)
    page.get_by_role("link", name="Accounts", exact=True).click()
    page.get_by_role("textbox", name="Search accounts").fill("")
    output = Path(__file__).parent / "artifacts"
    output.mkdir(exist_ok=True)
    page.screenshot(path=str(output / "accounts-desktop.png"), full_page=True)
    page.set_viewport_size({"width": 390, "height": 844})
    assert page.evaluate("document.documentElement.scrollWidth <= window.innerWidth"), "Mobile page overflow"
    page.screenshot(path=str(output / "accounts-mobile.png"), full_page=True)
    page.get_by_role("button", name="Toggle navigation").click()
    expect(page.get_by_role("link", name="Treasury", exact=True)).to_be_visible()
    page.set_viewport_size({"width": 1440, "height": 1000})
    page.route("**/api/backend/accounts", lambda route: route.fulfill(status=502, content_type="application/json", body='{"message":"Test: API unavailable"}'))
    page.get_by_role("combobox", name="Data source").click()
    page.get_by_role("option", name="Local API").click()
    expect(page.get_by_role("alertdialog")).to_contain_text("Connect to Local API?")
    page.get_by_role("button", name="Continue to Local API").click()
    expect(page.locator(".notice.danger")).to_be_visible(timeout=20000)
    expect(page.locator(".summary")).to_contain_text("Unavailable")
    page.get_by_role("combobox", name="Data source").click()
    page.get_by_role("option", name="Demo preview").click()
    expect(page.locator("tbody tr")).to_have_count(10)
    assert not errors, errors
    browser.close()
    print("PASS: accounts, search, create, transfer, journal pair, treasury, status, mobile, console")
